// <auto-generated />
using System;
using LMS.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LMS.Migrations
{
    [DbContext(typeof(LDbContext))]
    [Migration("20260204064641_UpdateInit1")]
    partial class UpdateInit1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LMS.Models.Book", b =>
                {
                    b.Property<int>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookId"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("CoverImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAvaiable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<DateTime>("PublishDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PublishedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("BookId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            BookId = 1,
                            Author = "Andrew Hunt and David Thomas",
                            CategoryId = 5,
                            CoverImagePath = "~/cover/b7.jpg",
                            ISBN = "978-0201616224",
                            IsAvaiable = true,
                            IsAvailable = true,
                            PublishDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PublishedDate = new DateTime(2021, 10, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Pragmatic Programmer"
                        },
                        new
                        {
                            BookId = 2,
                            Author = "Robert C. Martin",
                            CategoryId = 5,
                            ISBN = "978-0132350884",
                            IsAvaiable = true,
                            IsAvailable = true,
                            PublishDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PublishedDate = new DateTime(2023, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Design Pattern using C#"
                        },
                        new
                        {
                            BookId = 3,
                            Author = "Pranaya Kumar Rout",
                            CategoryId = 5,
                            ISBN = "978-0451616235",
                            IsAvaiable = true,
                            IsAvailable = true,
                            PublishDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PublishedDate = new DateTime(2022, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Mastering ASP.NET Core"
                        },
                        new
                        {
                            BookId = 4,
                            Author = "Rakesh Kumat",
                            CategoryId = 5,
                            ISBN = "978-4562350123",
                            IsAvaiable = true,
                            IsAvailable = true,
                            PublishDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PublishedDate = new DateTime(2020, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "SQL Server with DBA"
                        },
                        new
                        {
                            BookId = 5,
                            Author = "Robert C. Martin",
                            CategoryId = 5,
                            CoverImagePath = "~/cover/b6.jpg",
                            ISBN = "978-0132350884",
                            IsAvaiable = true,
                            IsAvailable = true,
                            PublishDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PublishedDate = new DateTime(2019, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Clean Code"
                        },
                        new
                        {
                            BookId = 6,
                            Author = "Martin Fowler",
                            CategoryId = 5,
                            CoverImagePath = "~/cover/b5.jpg",
                            ISBN = "978-0201485677",
                            IsAvaiable = true,
                            IsAvailable = true,
                            PublishDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PublishedDate = new DateTime(2018, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Refactoring"
                        },
                        new
                        {
                            BookId = 7,
                            Author = "Eric Freeman",
                            CategoryId = 5,
                            CoverImagePath = "~/cover/b4.jpg",
                            ISBN = "978-0596007126",
                            IsAvaiable = true,
                            IsAvailable = true,
                            PublishDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PublishedDate = new DateTime(2020, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Head First Design Patterns"
                        },
                        new
                        {
                            BookId = 8,
                            Author = "Jon Skeet",
                            CategoryId = 5,
                            CoverImagePath = "~/cover/b1.jpg",
                            ISBN = "978-1617294532",
                            IsAvaiable = true,
                            IsAvailable = true,
                            PublishDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PublishedDate = new DateTime(2021, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "C# in Depth"
                        },
                        new
                        {
                            BookId = 9,
                            Author = "Adam Freeman",
                            CategoryId = 5,
                            CoverImagePath = "~/cover/b2.jpg",
                            ISBN = "978-1484254394",
                            IsAvaiable = true,
                            IsAvailable = true,
                            PublishDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PublishedDate = new DateTime(2022, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Pro ASP.NET Core MVC"
                        },
                        new
                        {
                            BookId = 10,
                            Author = "Kyle Simpson",
                            CategoryId = 5,
                            CoverImagePath = "~/cover/b3.jpg",
                            ISBN = "978-1491904244",
                            IsAvaiable = true,
                            IsAvailable = true,
                            PublishDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PublishedDate = new DateTime(2017, 12, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "You Don’t Know JS"
                        });
                });

            modelBuilder.Entity("LMS.Models.BorrowRecord", b =>
                {
                    b.Property<int>("BorrowRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BorrowRecordId"));

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("BorrowDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("BorrowerEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BorrowerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ReturnDate")
                        .HasColumnType("datetime2");

                    b.HasKey("BorrowRecordId");

                    b.HasIndex("BookId");

                    b.ToTable("BorrowRecords");
                });

            modelBuilder.Entity("LMS.Models.Category", b =>
                {
                    b.Property<int?>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("CategoryId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Name = "Fiction"
                        },
                        new
                        {
                            CategoryId = 2,
                            Name = "Technology"
                        },
                        new
                        {
                            CategoryId = 3,
                            Name = "Science"
                        },
                        new
                        {
                            CategoryId = 4,
                            Name = "History"
                        },
                        new
                        {
                            CategoryId = 5,
                            Name = "Programmong"
                        });
                });

            modelBuilder.Entity("LMS.Models.Book", b =>
                {
                    b.HasOne("LMS.Models.Category", "Category")
                        .WithMany("Books")
                        .HasForeignKey("CategoryId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("LMS.Models.BorrowRecord", b =>
                {
                    b.HasOne("LMS.Models.Book", "Book")
                        .WithMany("BorrowRecords")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("LMS.Models.Book", b =>
                {
                    b.Navigation("BorrowRecords");
                });

            modelBuilder.Entity("LMS.Models.Category", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
